### PR TITLE
Added screenshots to individual state pages

### PR DESCRIPTION
**Pull request by kevee**
⚠️ Work in progress!

This addresses #76, but is missing date info for screenshots. Also, I'm just using `.pop()` to find the latest screenshot in the API array. @webmasterkai mentioned that maybe we can easily add date to the screenshot API, is that possible?

### CODE REVIEW

**Comment by kissane** [comment]
Hey @zachlipton maybe you can answer this? Or pass it to someone who can?

**Comment by webmasterkai** [comment]
Yeah, I'll add the date to the screenshots api.

**Comment by kissane** [comment]
Hey can someone resolve the conflicts on this one?

**Comment by kevee** [comment]
Note that the build broke due to another issue with the API that's currently being fixed.

**Comment by webmasterkai** [comment]
I parsed out the date and added it as `dateChecked` if you want it at some point.

**Pull request merged**
