### PR TITLE
State page twitter icons

### PR DESCRIPTION
**Pull request by schwartzadev**
Adds Twitter icons to the state pages instead of the Twitter link in text:

New:
image

Old:
image

### CODE REVIEW

**Comment by schwartzadev** [comment]
Hey it looks like the CI checks are hanging...if you click through to the Netlify details, it looks like they're done.

**Comment by lucasgonze** [comment]
@schwartzadev did it look to like the CI timed out some tests that did eventually pass? In that case we should look into fixing the tests.

**Comment by schwartzadev** [comment]
I'm not sure what you mean... For reference, the Netifly log indicates that everything worked successfully in ~51 seconds, which seems typical. I think the issue might be Netlify talking to the CI on Github: Netlify says the checks are completed successfully [on its site](https://app.netlify.com/sites/upbeat-lovelace-3e9fff/deploys/5e75084474cc510007ef553d), but Github isn't showing the same.

**Comment by lucasgonze** [comment]
yes, we understand it each other. It seems to me this is mergeable, but there is an issue with where Github is failing tests because it's not waiting long enough. Maybe there is an admin setting for that.

**Pull request merged**
