### PR TITLE
chore (docs): Changed language in volunteer form from jane/volunteer-form PR

### PR DESCRIPTION
**Pull request by amandafrench**
## Description

Removed workstream option for "management" on volunteer application form, changed "work" to "volunteer," and added option to "build data tools" for data applicants. 

## Related Issues

Addresses issue #817

### CODE REVIEW

**Comment by kevee** [comment]
Converting to draft while I lint and update tests

**Comment by amandafrench** [comment]
Sorry, @kevee, is there a new testable version of the volunteer form? The Netlify deploy preview links in the above all give me the old version of the Get Involved page.

**Comment by amandafrench** [comment]
Front end of form looks good, thanks -- all done. Submitted using test form and didn't get email, however, and still need to see if the email output needs formatting.

**Comment by amandafrench** [comment]
There's one small change this needs: the first option for *What would you like to volunteer to do?* is being used as the description of the field, so ALL form submissions are labeled "I'd like to help build data tools, collect data, or analyze data" I believe this is managed in volunteer-options.js. Not sure how to fix.

**Pull request merged**
