### PR TITLE
add note, source and bylines at the bottom #488

### PR DESCRIPTION
**Pull request by AaronMullan**

### CODE REVIEW

**Comment by goleary** [comment]
i see the note & source but no byline

**Comment by AaronMullan** [comment]
Whoops, thanks for catching that.  I was taking the instructions "Bylines will be updated with everyone's names later" to mean to not add the Byline for now.  But now that you point out that it is right there in the title of the Issue, it seems like the old byline should be there and it will be updated later.  Hold on, will update.

**Comment by AaronMullan** [comment]
Updated the branch.

**Comment by goleary** [comment]
looks good. Would you mind including a screenshot in the future so we can easily see what it looks like?

**Comment by AaronMullan** [comment]
Will include screenshot.  Thanks for that.

**Pull request merged**
