### PR TITLE
Added state grade

### PR DESCRIPTION
**Pull request by kevee**
Shows the data quality grade on the data page and individual state pages.

### CODE REVIEW

**Comment by webmasterkai** [comment]
Should we link to the twitter post that explains the grade system?

The score contains 4 simple components:

1. +1 for reporting positives reliably (only NV fails)
2. +1 for reporting negatives sometimes
3. +1 for reporting negatives reliably 
4. +1 for reporting all commercial tests 

https://twitter.com/covid19tracking/status/1240409388176666624?s=21

**Comment by kissane** [comment]
@webmasterkai Oh sure, it's a bonkers way to document but we don't have a page up yet and we're scrappy…

**Comment by goleary** [comment]
I'm working with Júlia Ledur and will have a PR ready shortly to add the data quality grade.
It will look something like this:
image

**Comment by webmasterkai** [comment]
Should we merge this so you can work from it easier?

**Comment by webmasterkai** [comment]
@goleary Feel free to rework as necessary. I figured it was probably easier having it in the template so you can cut/paste.

**Pull request merged**
