### PR TITLE
Fix table collapsing with empty values

### PR DESCRIPTION
**Pull request by bhays**
CSS fixes for #115 and #109.

### CODE REVIEW

**Comment by olivierlacan** [comment]
Hey @bhays can you name your PR more descriptively to explain what it changes please?

**Comment by schwartzadev** [comment]
I don't think this closes #109 but we should merge this anyways
image

#115 looks good -- thanks!

**Comment by schwartzadev** [comment]
I don't think I was clear about #109 -- the issue is that the borders are different widths, not that they are different colors. I reverted the color changes.

Thanks for fixing the table!

**Comment by bhays** [comment]
Can do, sorry about that.

The fixes include the `border-color` for the table header cells and adding `flex-grow` on `.state-flex-data` to avoid empty cells collapsing.

**Pull request merged**
