### PR TITLE
add twitter svg icon, replace twitter icon on states page

### PR DESCRIPTION
**Pull request by schwartzadev**
This icon is from Twitter's Brand Resources page -- I modified it by changing the color of the icon from white to black and removing the background

### CODE REVIEW

**Comment by schwartzadev** [comment]
I would like to add the Twitter icon to the individual state pages as well, but I'm not sure where to put it, from a design perspective... Any suggestions?

**Comment by webmasterkai** [comment]
Can you double-check the "Best current data source" that got added back in here?

**Comment by schwartzadev** [comment]
⚠️ WIP

**Comment by schwartzadev** [comment]
There it is! Sorry about that.

image

**Pull request merged**
