### PR TITLE
fix(charts): remove focus from container, re: #429

### PR DESCRIPTION
**Pull request by AaronMullan**

### CODE REVIEW

**Comment by vijaysharwar** [comment]
@AaronMullan @goleary I know this is merged, but I would recommend reverting this for accessibility. Without `outline`, if you tab navigate to this UI, a keyboard-only user can't tell where the focus is.

Further reading:
https://webaim.org/techniques/keyboard/
https://webaim.org/blog/plague-of-outline-0/
https://www.w3.org/TR/WCAG20-TECHS/G202.html

**Comment by AaronMullan** [comment]
I think the main thing people were not liking was the fact that the whole div gets focus, not just the  button.  I'm trying to look at a way of making only the button get focus.

**Comment by AaronMullan** [comment]
I can just put it in another div.  Here it's in the middle, which I don't mind, but I guess that's not the design.

Screen Shot 2020-04-10 at 4 47 25 PM

**Comment by AaronMullan** [comment]
Or float the button to the left:

Screen Shot 2020-04-10 at 4 52 14 PM

**Comment by vijaysharwar** [comment]
@AaronMullan we can do it by [adjusting the width](https://github.com/COVID19Tracking/website/blob/dashboard-gatsby/src/pages/dashboard/map-container.scss#L72) perhaps.

Note changes I'm making in another PR, though:
- Changing the ID to a class: https://github.com/COVID19Tracking/website/pull/494/files#diff-06cd32530420ab6e5e788a7f09e1f4a3R70
- Setting a `max-width` attribute on my new toggle to restrict the size: https://github.com/COVID19Tracking/website/pull/494/files#diff-d99b5a549ac78593a54c2878d296386cR62-R66

Might be easiest to revert this first, merge PR above, then fix the width of the original map toggle last.

Also note that the `outline` style change is very brute force, and removes outline for all elements in `.container` (including the global top nav).

**Comment by AaronMullan** [comment]
Anything that is the simplest path forward sounds good to me. I hadn't realized focus was important for those reasons. The solution I came up with was just to make another div as the container for the button, give the container a width of 100%, and take the 100% width off the button div.  Once your PR's are merged one of us could do that.

**Comment by goleary** [comment]
a PR from either of you reverting it to the accessible state will be welcomed.

**Comment by AaronMullan** [comment]
PR #500 addresses this.

**Pull request merged**
