### PR TITLE
[WIP] Redirect API endpoints

### PR DESCRIPTION
**Pull request by kevee**
## Description

Based on a sample of 32,000 API calls being proxied to the old API endpoint at three different times of the day, this PR adds redirects to all possible used combinations of old API calls.

### CODE REVIEW

**Comment by kevee** [comment]
Sample endpoints:

https://deploy-preview-746--upbeat-lovelace-3e9fff.netlify.app/api/states?state=CA
https://deploy-preview-746--upbeat-lovelace-3e9fff.netlify.app/api/statesdaily?state=CA&date=20200401

**Comment by webmasterkai** [comment]
Have you tried making a CORS request? I'm getting errors. You could try doing an internal proxy instead of a redirect.

You can remove any `.html` endpoints from the redirects. There is only CSV and JSON endpoints there.

As we have discussed many times, making these changes will break functionality for certain users that use query string combinations that are not accounted. For example `?grade=B` will not filter the list.

What is gained or improved by these changes?

**Comment by webmasterkai** [comment]
Also, I remember the CSV files being used with query args. It doesn't look like there is provision for that in these redirects.

**Comment by kevee** [comment]
Hi, Kai! So the redirects do support CORS. Here's the redirect header:
```shell
curl -I https://deploy-preview-746--upbeat-lovelace-3e9fff.netlify.app/api/statesdaily?state=CA&date=20200401
[1] 285
m043-300-28109:Documents mill5935a$ HTTP/2 301
access-control-allow-origin: *
```
and the v1 URL it redirects to:
```shell
curl -I https://deploy-preview-746--upbeat-lovelace-3e9fff.netlify.app/api/v1/states/daily.json
HTTP/2 200
accept-ranges: bytes
access-control-allow-origin: *
```

[Here's a codepen showing CORS working with the redirect and the old API URL](https://codepen.io/keveemiller/pen/JjYrPVv?editors=1010)

I agree that we want to not break anything as much as possible, but when I pulled the log of requests, I only saw `state` and `date` URL parameters, no like `grade=` entries. That prompted me to start this PR because it seemed like there weren't any edge cases that we weren't considering.

The idea behind them is to get all of our current API users hitting the same URLs, and to be able to track API usage through analytics. Proxies don't give us that ability in Netlify.

**Comment by ccheever** [comment]
This looks good to me. Definitely makes things easier that only those 2 filters were being actually used.

**Comment by webmasterkai** [comment]
I forgot about the analytics not only showing file views and not counting proxy requests. That's a valid point.

I've looked at some logs and of the top 2000 or so combinations. The only combination that isn't covered is folks using a combination of `state` and `dateChecked` field instead of `date` on /states/daily (`/states/daily?state=TX&dateChecked=`). Could we proxy that one combination? All other combinations not accounted in these redirects happen fewer than once every 8 hours. If someone complains they could be sent to the old covid.cape.io url and told it's available there but an "unsupported" option.

We will want to add some provision for CSV files
- `/states/daily.csv?state=DC&date=20200404`
- `/states/daily.csv?date=20200307`
- `/states/daily.csv?state=NY`

**Comment by kevee** [comment]
Cool, thanks for the edits. We *do* see a lot of requests for `api/statesdaily` for some reason, so I think we should leave that redirect in there.

**Comment by kevee** [comment]
⚠️ I am going to hold off on merging this PR until early AM. Also, Netlify is being super nice and is pulling all of their CDN data for us to take a look at.

**Pull request merged**
