### PR TITLE
fix(charts): make links have state names #463

### PR DESCRIPTION
**Pull request by AaronMullan**

### CODE REVIEW

**Comment by AaronMullan** [comment]
It's weird, the 'Resolve conflicts' button is greyed out.  And there's really only one line of one file that's changed, so I'm confused where the conflict is coming from.

**Comment by goleary** [comment]
@AaronMullan I've seen some weird issue like this before.  Just merge the latest `dashboard-gatsby` to your branch from the cli and then push the result.  There may not even be any conflict to merge...

**Comment by AaronMullan** [comment]
OK, that seemed to work!

**Comment by goleary** [comment]
cool, thanks!

**Pull request merged**
