### PR TITLE
fix(dashboard): updated text content and formatting 576

### PR DESCRIPTION
**Pull request by goldfarb**
[576](https://github.com/COVID19Tracking/website/issues/576)

Made text updates

- Close the space here in “it ’s” 

image

-Deleted mid-page header (“On this page, you will find …“) and change previous sentence to "If you plan to display data from the COVID Tracking Project yourself, please closely follow these design and visualization guidelines"

image

- Cut “sort of” 
image

- Cut this paragraph: "By comparing the positive ...

- fix apostrophe 
image

- updated link for John Burn-Murdoch

- added a link for FactCheck.org

- removed links from byline names

### CODE REVIEW

**Comment by goldfarb** [comment]
I also removed the note (per [Erin](https://github.com/COVID19Tracking/website/issues/576#issuecomment-614204126))

**Comment by goldfarb** [comment]
I did _not_ update Virgin Islands to US Virgin Islands -- I think that comes from how the 'state' is named in the data, so it'll take a bit more to replace the default name

**Comment by goldfarb** [comment]
Two questions:

1. Shall use [this](https://github.com/COVID19Tracking/website/issues/576#issuecomment-614198413) intro text
2. Should straight quotes (&quot; / ") be  replaced with smart quotes (&rdquo; / ”)?

**Comment by julialedur** [comment]
great, thanks! 😄 

- you can remove the link from "these design and visualization guidelines" cause we meant our guidelines lol 
- yes, let's use Erin's intro text! 
- about the quotes, let's use &#8220;  and &#8221; they're more curvy

**Comment by goldfarb** [comment]
- Updated quotation marks.

- Updated text.
 
- Removed the self-referential link

**Comment by goleary** [comment]
just resolved some conflicts @jeremiak can you take a look at this again and merge if it looks good.

**Comment by schwartzadev** [comment]
Hey @goldfarb thanks for the fixes! :tada: It looks like you left the `cumulativeTotal` variable in the CDC Comparison Container description: `{format('.2s')(cumulativeTotal).replace('M', ' million')} tests`
(from `src/pages/dashboard/_CDCComparisonContainer.js:108`)

In turn, this seems to be causing Netlify to fail.

```
3:37:27 PM: error Building static HTML failed for path "/dashboard"
3:37:27 PM:   104 |     <section>
3:37:27 PM:   105 |       <div>
3:37:27 PM: > 106 |         <p>
3:37:27 PM:       |         ^
3:37:27 PM:   107 |           As of today, the COVID Tracking Project has identified more than{' '}
3:37:27 PM:   108 |           {format('.2s')(cumulativeTotal).replace('M', ' million')} tests
3:37:27 PM:   109 |           administered across the country, a count significantly higher than the
```

I'm not sure if you wanted to: 

1) Remove the `cumulativeTotal` field from the description
2) Keep the `cumulativeTotal` field in the description

I'm hoping to move this forward soon :smile:

**Comment by goldfarb** [comment]
@schwartzadev If I'm looking at the same thing you are, that whole paragraph should be coming out, as should the `const cumulativeTotal = sum(covidData, d => d.value)`

https://github.com/COVID19Tracking/website/commit/5ae80c2e28e25f6c509b0cdabca13f76b2dc6ce5

So I would say 1, remove

**Pull request merged**
