### PR TITLE
Individual state pages

### PR DESCRIPTION
**Pull request by kevee**
Per #50: Used 11sy pagination to create a single page per state with basic information and a table of historic information.

### CODE REVIEW

**Comment by kissane** [comment]
Hey @beep (or @Wilto) could you have a look at this tomorrow and give it a usability check? I have been trying to make 20 minutes to debug my dev environment so I can compile locally for about ten straight days and I am still not there.

**Comment by webmasterkai** [comment]
Thanks for your help with this! Looks great to me. I've merged in the portion that builds the individual pages but left the link to the state pages off of the `/data` page for now. It will need to be replaced with `<a class="state-link" href="/data/state/{{ state.stateName | slug }}">` when we get final approval from the rest of the team.

Individual state pages can be seen like so https://covidtracking.com/data/state/florida/
or https://covidtracking.com/data/state/new-york/

**Comment by olivierlacan** [comment]
> Hey @beep (or @Wilto) could you have a look at this tomorrow and give it a usability check? I have been trying to make 20 minutes to debug my dev environment so I can compile locally for about ten straight days and I am still not there.

Hit me up for debugging help tomorrow if you still need it.

**Comment by beep** [comment]
Mornin’ all. I added a few small style refinements in #73, and also lit up the navigation on the individual state pages. There’s more we could tweak on the state pages, of course, but let me know how this PR looks to you!

**Pull request merged**
