### PR TITLE
feature(dashboard-gatsby-bar-chart): added total state deaths bar chart

### PR DESCRIPTION
**Pull request by melbee**
This migrates all functionality from original version and completes all the requested updates from [this open issue](https://github.com/COVID19Tracking/website/issues/483) except for the layout request.

I recommend all layout updates be done after all core charts and functionality are added and finalized to apply changes consistently at once across all components (i added more on this in the open issue)

Screen Shot 2020-04-12 at 3 32 41 PM
Screen Shot 2020-04-12 at 3 33 01 PM

### CODE REVIEW

**Comment by melbee** [comment]
This migrates all functionality from original version and completes all the requested updates from [this open issue](https://github.com/COVID19Tracking/website/issues/483) except for the layout request.

I recommend all layout updates be done after all core charts and functionality are added and finalized to apply changes consistently at once across all components

Screen Shot 2020-04-12 at 3 32 41 PM
Screen Shot 2020-04-12 at 3 33 01 PM

**Comment by goleary** [comment]
the change in size of the horizontal bars is a bit jarring to me but i'll let others weigh in.  Will merge for now and any changes to that can come in future PRs.

**Comment by goleary** [comment]
also for newly added charts we should also add them in storybook. again not a blocker for this but something to think about as we add new types of charts.

**Comment by julialedur** [comment]
yeah, i agreee @goleary, it gets quite long when expanded. will think on it

**Pull request merged**
