### PR TITLE
Add press links

### PR DESCRIPTION
**Pull request by schwartzadev**
This replaces the static press links on `index` with ones from the API

### CODE REVIEW

**Comment by kissane** [comment]
oh cool next please tell me how this works, I was editing it all in the CMS

**Comment by webmasterkai** [comment]
There's another spreadsheet https://docs.google.com/spreadsheets/d/1-lvGZ3NgVlda4EcF5t_AVFLnBqz-TOl4YZxYH_mJF_4/edit#gid=0

**Comment by kissane** [comment]
Who's maintaining this one?

**Comment by schwartzadev** [comment]
I was working with Jeremia on this one but Jeremia knows more about it than I do

**Pull request merged**
