### PR TITLE
fix(choropleth): update color schemes

### PR DESCRIPTION
**Pull request by goldfarb**
Uses [updated gray scale color](https://github.com/COVID19Tracking/website/issues/349#issuecomment-612488846 ) schemes for death maps.

Fixes COVIDTracking/website#349

### CODE REVIEW

**Comment by julialedur** [comment]
thanks, @goldfarb ! 😄 
could you include screenshots in your next PRs, please?

**Comment by goldfarb** [comment]
Before: 
image

After:
image

**Comment by vijaysharwar** [comment]
Does the grey palette in `colors.scss` need to be updated as well?

Note the separate Issue to use those colors in `_Map.js` to DRY things up: https://github.com/COVID19Tracking/website/issues/469

cc @beep

**Comment by goleary** [comment]
i agree with @vijaysharwar we should be using the colors in colors.scss so we can update them from one location.

**Comment by julialedur** [comment]
good call! can one of you update colors.scss?

**Comment by beep** [comment]
> Does the slate palette in colors.scss need to be updated as well?

As of https://github.com/COVID19Tracking/website/pull/461, we’ve already got the updated colors in there! (The palette specified in #440 and #465, that is.)

**Comment by vijaysharwar** [comment]
I'd say if the colors are updated in the SCSS, we can go ahead and merge this PR for now. Then circle back and DRY things up in https://github.com/COVID19Tracking/website/issues/469.

**Pull request merged**
