### PR TITLE
Add Washington Post story in Press

### PR DESCRIPTION
**Pull request by olivierlacan**
Since The Washington Post mentioned us today, I thought it'd be good to add it to press mentions.

Took the opportunity to replace all press logos with their SVG equivalents sourced from Wikimedia Commons.

Before: 
image

After: 
image

The biggest one (WaPo) is 11kb, most are less then 4kb instead of 8 to 25kb for the PNG and JPG versions we had previously. This will help all mobile users especially since this is the landing page for the project.

A lot of the previous logos also included a lot of unnecessary white space which made placement and sizing more difficult.

## Before
image

## After
image

### CODE REVIEW

**Comment by webmasterkai** [comment]
I LOVE SVG!

There is a [spreadsheet](https://docs.google.com/spreadsheets/d/1-lvGZ3NgVlda4EcF5t_AVFLnBqz-TOl4YZxYH_mJF_4/edit#gid=0) now for tracking press. We'll need to get it added there too so future website versions continue to display it.

**Comment by olivierlacan** [comment]
If anyone has any concern about SVG BTW: https://caniuse.com/#feat=svg

@webmasterkai Let's tackle the spreadsheet integration next maybe. This is a quick win for now on the filesize front at least.

**Comment by olivierlacan** [comment]
Oh and the wapo piece in already in there and marked as needing to be shown on the site.

**Comment by hammer** [comment]
Is it easy to get this line of logos to wrap on mobile? Currently they make a very long line while the test wraps to my view.

**Comment by olivierlacan** [comment]
> Is it easy to get this line of logos to wrap on mobile? Currently they make a very long line while the test wraps to my view.

It's the next thing I want to tackle, needs some flexbox love from @schwartzadev

**Comment by olivierlacan** [comment]
@hammer Filed in #155.

**Comment by kissane** [comment]
BTW I already added this piece to the spreadsheet. This looks great @olivierlacan! OK to merge or are you waiting for flexbox help?

**Comment by schwartzadev** [comment]
I'll do the flexbox updates today or tomorrow in a new PR.

**Comment by olivierlacan** [comment]
Thank you @schwartzadev!

**Pull request merged**
