### PR TITLE
fix(design): Remove style collision removing space

### PR DESCRIPTION
**Pull request by JackHowa**
- Test and didn't see updated snapshots 
- Noticed the react components did have the child shown of the space, but, due to collisions, wasn't rendering 
-> investigation here showed me https://github.com/COVID19Tracking/website/issues/1608#issuecomment-731599590 (thanks @ivarvong )

- see source space between `:` and `Civil services`

before: 

Screen Shot 2020-11-23 at 6 20 01 PM
Screen Shot 2020-11-23 at 6 20 35 PM

after: 

Screen Shot 2020-11-23 at 6 19 18 PM
Screen Shot 2020-11-23 at 6 18 41 PM

### CODE REVIEW

**Comment by ivarvong** [comment]
Does removing "display: flex" affect the behavior of the component(s) using it? (I haven't checked)

If it's feasible, fixing the selector collision seems desirable.

**Comment by JackHowa** [comment]
yeah true, the underlying issue is a config

**Comment by JackHowa** [comment]
> Does removing "display: flex" affect the behavior of the component(s) using it? (I haven't checked)

From playing around with clicking the button and hovering vs prod, I haven't noticed a difference

**Comment by JackHowa** [comment]
huh updating to length did not fix the issue 

Screen Shot 2020-11-23 at 7 04 38 PM

via https://github.com/webpack/loader-utils#interpolatename

**Comment by JackHowa** [comment]
yep updated ... added back the `display: flex` with the longer longer.

**Comment by JackHowa** [comment]
@ivarvong as you alluded to, whether we want to still align right for the source is open. Seems like that was accidentally shown on the left side previously for all breakpoints

**Review by schwartzadev — APPROVED** [review]
Awesome, looks good to me! Thank you both @JackHowa + @ivarvong

**Pull request merged**
