### PR TITLE
fix(nav): Fixes bug where clicking search button did not close search bar

### PR DESCRIPTION
**Pull request by scandycuz**
Fixes issue #1034 (Search bar won't close)

### CODE REVIEW

**Comment by scandycuz** [comment]
When it runs the 'Test deployed API/test' it is unable to connect to Netlify (displays the message 'Url unavailable, retrying...'). I'm not sure how to get it to connect, any help is appreciated, thanks.

**Comment by kevee** [comment]
Just FYI @schwartzadev is working on this but probably won't be able to review until the end of the week.

**Comment by schwartzadev** [comment]
This looks great @scandycuz! #1034 definitely is resolved :+1:

I noticed another related issue, though. Would you be able to tackle it in this PR as well?

Expected behavior:
1. open search bar
2. click on purple `SEARCH` text
3. nothing happens

Actual behavior:
1. open search bar
2. click on purple `SEARCH` text
3. the search bar closes*
4. the nav remains invisible

*the `SEARCH` text remains, but the `<input>` collapses. See this image:
image


If it's easier, I'm OK with clicking on `SEARCH` closing the search bar, so long as it also re-displays the nav.

**Comment by scandycuz** [comment]
Thanks @schwartzadev ! No problem, I'll make the change.

**Comment by schwartzadev** [comment]
One more, if you don't mind @scandycuz:

Expected behavior:
1. Open search bar
2. Click away from window (outside of the page scope, like in the grey space in dev tools outside of the frame or into another application)
3. Search bar closes, nav bar re-appears

Actual behavior:
1. Open search bar
2. Click away from window
3. Search bar stays open, nav remains hidden

**Comment by schwartzadev** [comment]
@scandycuz Just a heads up: I merged this already, but I'm going to put the two outstanding items into an separate issue to keep things clear :+1:

**Comment by schwartzadev** [comment]
Aha you're ahead of me! #1057 and #1058 tysm!

**Comment by scandycuz** [comment]
Lol, no problem

**Pull request merged**
