### PR TITLE
Final legal updates

### LINKED ISSUE #1001: Final legal things from The Atlantic
The legal folks have sent two more things we need to implement, if anyone is around:

- Privacy Policy link ([linking to this page](https://www.theatlantic.com/privacy-policy/))
- Copyright notice: CovidTracking.com Copyright (c) 2020 by The Atlantic Monthly Group. (CC BY-NC 4.0))

I am not a lawyer, but I would like that copyright thing to link to our licence, please.

Many thanks.

### PR DESCRIPTION
**Pull request by schwartzadev**
## Description
Fixes #1001
* Adds the privacy policy to the footer
* Adds the copyright notice to the footer

(FYI #996 is in progress, which will make the ever-growing footer a little nicer in the interim)

### CODE REVIEW

**Comment by kevee** [comment]
Let's go ahead and link `(CC BY-NC 4.0)` in the footer to the License page.

**Comment by schwartzadev** [comment]
@kevee fixed in https://github.com/COVID19Tracking/website/pull/1002/commits/88c94b1dd4a8aeff8168ae37b5234bf5f65c7f0d :+1:

**Comment by kissane** [comment]
Looks great from my side

**Comment by kevee** [comment]
Updating then merging.

**Pull request merged**
