### PR TITLE
chore(press): Add Boston Globe

### LINKED ISSUE #651: Featured on the front page of The Boston Globe
Hi everyone!

The site was just featured as the main source in today's front-page article of The Boston Globe:

https://www.bostonglobe.com/2020/04/18/nation/amid-flurry-national-coronavirus-data-massachusetts-remains-hot-spot-infection/

...so well done! You're cited near the top of the article as well as in their main infographic. I've added the Globe to `homepage-press.yml` and its vector logo in #652. Let me know if I should add `featured: true` as well? I think it's a pretty big deal! 👍 

I'm also not sure where the articles on the In the Press page are pulled from, I'm guessing a spreadsheet that you all have access to? If I'm missing it then just let me know. :)

Screen Shot 2020-04-19 at 10 18 58 AM

### PR DESCRIPTION
**Pull request by jakejarvis**
Fixes #651

### CODE REVIEW

**Comment by julialedur** [comment]
hey, @jakejarvis! thank you for this! 😄 
could you add a screeenshot, please?

**Comment by julialedur** [comment]
can we add some margin between the logos and the list of stories? 
it feels super busy now: 

Screen Shot 2020-04-22 at 4 45 22 PM

**Comment by schwartzadev** [comment]
@julialedur I just ran the build, which is [live here](https://5e9c5ee3018b9c0007ebfe6d--upbeat-lovelace-3e9fff.netlify.app/about-project/in-the-press/).

Here's a screenshot as well:
image

**Comment by julialedur** [comment]
@schwartzadev cool! should i open a new issue for margin?

**Comment by schwartzadev** [comment]
Yes please @julialedur 👍

**Pull request merged**
