### PR TITLE
Added state navigation

### PR DESCRIPTION
**Pull request by bgamrat**
Added state navigation to right side

### CODE REVIEW

**Comment by schwartzadev** [comment]
Thanks for the addition!

If you don't mind, I'm going to make some minor changes to the formatting and the mobile behavior.

Right now, this nav takes up a lot of valuable real estate on mobile devices so I'll try to find a fix for that.

image

**Comment by hammer** [comment]
Could we do this with a map too or instead?

**Comment by schwartzadev** [comment]
Ooh that could be cool...Do you mind if I do the abbreviations in the meantime and then look into a map?

**Comment by schwartzadev** [comment]
Desktop
image

Mobile
image


I really don't love the arrow placement -- from a UX side, it's not clear what it means. Instead I would add a `(return to top)` link where I placed the two grey lines.

image

@bgamrat Do you want to do that? If not, I can take care of it 👍

**Comment by bgamrat** [comment]
No worries on making changes - it’s your stuff

Thank you for asking

**Comment by schwartzadev** [comment]
image

image

All done!

**Comment by bgamrat** [comment]
Nice!

**Pull request merged**
