### PR TITLE
V2 summary tables design

### PR DESCRIPTION
**Pull request by schwartzadev**
Based on designs from @beep and co.

This work is in progress. @kevee -- please hold off on merging for now.

Edit: **many table values are missing since the API is not yet configured. Check todos for more detail.**

### CODE REVIEW

**Comment by schwartzadev** [comment]
This implements the `tablesaw` library for adjusting summary tables.

This has some performance implications on the client-side, namely that the `/data/` page has to render ~60 `tablesaw` tables, which takes 10-30 seconds after the first paint on my machine.

For me, this makes this page feel very clunky. I would urge others to pull this branch and check it out for themselves. We should probably discuss as a team before merging.

**Comment by beep** [comment]
> For me, this makes this page feel very clunky. I would urge others to pull this branch and check it out for themselves. We should probably discuss as a team before merging.

I can’t get gatsby up and running, but if we’re seeing _10-30 seconds_ of lag, I’d be inclined to just overflow the tables for now. We can figure out a Fancy Adaptation Approach™ at some point after launch.

**Comment by schwartzadev** [comment]
I'm going to remove the values that are missing from the API

**Comment by schwartzadev** [comment]
Ok -- this looks good to go :+1: -- tables scroll on smaller viewports and behave like tables on larger ones.

**Pull request merged**
