### PR TITLE
[⚠️WIP] feat: Cypress testing

### PR DESCRIPTION
**Pull request by kevee**
Work in progress. This PR:

- Adds [Cypress](https://www.cypress.io/) for end-to-end testing
- Defines a few simple tests to QA the site and some client-facing interactions
- Defines a React component test for text formatting
- Adds CircleCI

I'm leaving this as draft while we test the CircleCI integration with the repo.

### CODE REVIEW

**Comment by kevee** [comment]
Scheduling this to be merged on April 17:

- [ ] Merge branch
- [ ] Enable Github checks in CircleCI
- [ ] Only let CircleCI run on PRs
- [ ] Notify #website they need to pull from master to get testing and make sure their PRs work

**Comment by gitjeff05** [comment]
Looks cool, @kevee. Dumb question: will we be migrating away from Jest? Or is cypress in addition to our Jest tests? I haven't heard any chat about cypress in the channels so excuse me if this has already been discussed.

**Comment by kevee** [comment]
@gitjeff05 - There's still a place for Jest - unit testing the site, QA testing output (what you've been doing), and testing APIs. Cypress is a much heavier stack for testing rendered output that we can't do in Jest.

**Comment by kevee** [comment]
Closing for now as testing revealed CircleCI setup would be more complicated than thought. I'm opening another PR for more manageable testing soon.

**Pull request closed without merging**
